---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:5saPTuqv6Xc2pkDtm4NOmF/fC7OLn9+OaXRf4A18UfshAdXF7dQdjDtVVxfTht6P94xFyS8=,iv:t2bmhaf7Ss7+uM1tlWIGImJszq7FYMtPWqn4XvsiT38=,tag:3YFepu0snzMeoY1/6j3asA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2QWV1ekpGckNyaEluRWxi
        bjZZTWZManB1blFKMC9qZVdsU0IzVGhHSVFNCkNZd3lUUjFsMlQyUkNOVmZ0bHJS
        ZEtscnlFRVYvWFZwVUx6ekk2SU1PNHMKLS0tIEljTWJzZHhyVUFhdEREaDM5SWtX
        T29Gck9YNnQwQXdreWhQSmR3SlY1RXcKTEScTV0cac+gEdcpFqTnWR/FPtubdYyq
        FmqAQDOklE3ccO5K3C5TZ/OsDKMLwsEL6IFw+2MZc/2LNjzFh/ws3A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ez6ym82keucyk5449ngczknhpg5u846f32xvvqwtrugyscnakgxqg6vtpa
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-18T22:40:57Z"
  mac: ENC[AES256_GCM,data:p5WEUGPk+wwrYU4fSXbJ2SvrSLzZVHMwgJMetEvZjVOt9Nt6+tZvqiufX2hq0ppQ5SI0N6iJIbMVIAXuGTQ16p+cRjDJBpaA2SfuS/E0C3aQqNBIV6cuBPCG6FNSYW4rPTtOIWKvG6U6y84DcaLcCy0G2upwl2pR5dcQhkEo0Ok=,iv:PjsOC0695n1R3CyUG/kAnWvXja+YYEatlodbYjG6Ex4=,tag:syxjo3v0B+tKPHuCzREVcg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
