---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:GfhO8vFrt43WeiiM6A==,iv:Ka9MecBLUpFCkRlf9H1xstjvsqkzm5jIPBqGhD0XqMI=,tag:DfwUbBmfBNQUpf+Q8DJuBQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxeG4xaEh0Q0gyUnhONkEz
        NW5jcTdKWi9Eek9vSzRPa3VZSEsxcEt2b1IwCkJ6dEgvSkRmQnptOFkzY3Jucnoz
        MDdCM2ZDcHhMVmZpODlha0d4YW1zOUkKLS0tIDVlWXFNaG5QMGNYOTVnTzFkUmlS
        WFV6cVRJbytscmFQY1h6aG9uWWZYSzQKsHxKSkaBwlWQmQXaKqx7+ByMPbx1aDV3
        7sw2JqtuXzAJR8d8Ieowe2WAPnlDsi88wzYaQ6LIIsRTNpbY5YTRfA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ez6ym82keucyk5449ngczknhpg5u846f32xvvqwtrugyscnakgxqg6vtpa
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-18T22:40:57Z"
  mac: ENC[AES256_GCM,data:5RJT5rlxnhA+5n+qGcnpj2dTfAsL7xCjihxp5Bo4pLGhcAnfBVQZL9xyID5h7jOOxeCvorFXYdZqsj49NbU/OMKvnXwHG9VakAuiJnlDcqUkbyolGA27cX2AJAb2pGy0/ZhydS4IKz/8UcR/mVltLyeBCoNLSG7+yKOOHKQU87k=,iv:VsDf8Gxi11MvVTX1NpOY8FEIWFInwhf6fWKd3l+10XU=,tag:6JOUAPk0/dbrnqoMCIYJjg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
