---
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:C5I5uri2LnY2A38SIRVrmwDeFBGzQ3Z5hQaqYyyrN6g=,iv:dICTfEGD7KbfxEguACQ1xuVLAyptp0mJPAZDMYGiQsE=,tag:QeovgXbKd/6kVoqi/FarTw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIajlkQWdBRHR5bDdzb3NG
        TmhsS0dxY2JDT1RCOHYxL2lwbC9KY1BuZHljCjJGZW9JcTJzUUZHbFRBczNLTG9w
        WE4rZ044MzNnNUxUWWJNcWNSdEpnOEUKLS0tIGM4bk1tWnVFZEdtU01yNjl4YlN5
        eUlwaWgzblRuWjRsaUwxcUZHejYxVnMK9eo6W3PUvJBd/HYFFGoaR0eRZws5kcio
        JE48AUGbiDUGYh6C3G58plmtMxJmWoxa5/YtELNtim7kk8rafLhTLQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ez6ym82keucyk5449ngczknhpg5u846f32xvvqwtrugyscnakgxqg6vtpa
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-18T22:40:57Z"
  mac: ENC[AES256_GCM,data:Z7m4fXDnKGN2zuxk38VxMdXEgblSbKAXg5jIC05vobnJZhwLW5KDpryKDVgnaEufU3/2NCZ58Z7AYqwlX7kidD70h2gC8BAcZk8Sy69eDlFqwOm4Ztb3+B4ddLi0c7lJPiKRCjOnxN4fLL3dNeraT004s9GHSiH+PpQITiIfCIE=,iv:JLOstWu2pcCrVXySdOmXF+pzesx1SAMMydE9jIN/fVQ=,tag:NVqKfot00UsNreZJ2Rxw3g==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
