---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflare-tunnel
spec:
  endpoints:
    - dnsName: "external.${SECRET_DOMAIN}"
      recordType: CNAME
      targets:
        - "bd05ebef-3752-4ba0-b70e-55ce5ff0a72e.cfargotunnel.com"
