---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:KVLQQywLjA5ZFSsQCJ6jzQ7/f6z/UQa3PjTSAAiYOiR5WnvALNDtZvdk8SRkGdVNE9Ucc3gf4m6zYPQ84hLkALT6lC5uUSvqsWmOWW16L/inSomsKlvamd4f+DgKx2AC+rK2GONgcF21jusyND8EVLjeqTcyflm9LQBWVwplMIxrTxPNT/WWXhu9HjcHy0H9dQ+8fuUgsuB+i8z+nL3FTz3CCqExdf79LmgtkK0ZwYD9JHOp,iv:q8ubeWx9ATbMFiLHRKxi5Xn1WdUC4W9SF2tMNeLobJM=,tag:qrDBPQIBF5/Kbx008Bos+w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOMXE5VWdwV3ByMXhDZ2o2
        a2c0SU1LbEREYURjczY2ZHMvRmJlNWFQS2dJClQ3Y1A2UVVic2w5Z2RHMWVHanpm
        VWVhN0dFZTQ3S29Hb0ZaalNoSUhqR2cKLS0tIDlLaWJ2RldUUEk3Y3hNZnN5c2ta
        UC9naGREQldMZ21nVmZMSVAvT2t4MkUKhI4tmRRaY1VIohp3l4HWYTlXsAVS6CeX
        OKdbG+tOdNTg/u7eiV1yALaaZT/R+DrlmOXRiNm/+VYMIzB1dr1/CA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ez6ym82keucyk5449ngczknhpg5u846f32xvvqwtrugyscnakgxqg6vtpa
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-18T22:40:57Z"
  mac: ENC[AES256_GCM,data:9MumXX85fkohu0iPFy3MNSnH4cz5G/uZtCpu/rxAXBf4VEHs4AZ9b9V4ABSTTytHH4LDR2HL7GLVlHRdjUiBvJ8RUD1khrfO2a9Hkq01S9zri4s+MByn61h59/1+wc1mhnUi01MHwmYTn61kPH8+MgcrxpRbSJak0r32O6DVaSY=,iv:s5/w/FjxrrrAxsXIJJWSmcj0UV107BB8nmAuT3QrNGQ=,tag:XUy5gnwtmqG0+YMEZGUWSQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
