---
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:+T7lXuUbGByhuoywFbwwwCSH8LeyCBNjwnEj1wNckwzoXUD+W+agJ5nE/5tQxkcDAM+6wUE=,iv:ii3TN0GJErAtCiPx78oGfAzfSd+Hq2ZErkKQ9Njf/N0=,tag:sYFq6yrA+lXHvE08yfrQng==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiR3lPeFZRSWJDbXM0bnQz
        Y2I5Rm01eUpPQnhid1VSZnUwbWlYQk1YV1hjCjJmdGlPRmRCYXJ0TnNiM2V2cWdG
        ZVNNUHhDanNRMDN3UHBHUzZaeTZpTU0KLS0tIHNKamxCNEZzQWd6aVF3Slg5dEU0
        ejZuMWpGUVZCV1FxU3g0dmwrT2xjdlEKYpxdzVjDj82r9mYoucpUCMH1y6HrWXE/
        VZKzZg/UtDbBrNUKh+YGHOF9VU0WgGBRxj2l/gjUi5xWkzcPj3AN1w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ez6ym82keucyk5449ngczknhpg5u846f32xvvqwtrugyscnakgxqg6vtpa
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-18T22:40:57Z"
  mac: ENC[AES256_GCM,data:GeicVnTTwl3wInBBN/ja3Uxt+nKucHWoTA5KNdolzoXsxJie9yqpPznWmGQgZ4mzo3TEObwuPGGqou3O5DtLiTmo5/tRKlHJdpFJYfZRDf340xsEdezu/ih9fxxA60sGaGMLv4f0zBLHQt7pAMHFmU58AA/+PVw1190vPd2jEvc=,iv:JjkxTPkOv3b4haL14CKCZMJX3QeZkgQ8Xc6UEwbnfpE=,tag:QqEy1w30FjSxD86PGGR6IA==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
