---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://192.168.1.20:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "192.168.1.20"
additionalMachineCertSans: *sans

clusterPodNets:
  - "10.42.0.0/16"
clusterSvcNets:
  - "10.43.0.0/16"

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "k8s-0"
    ipAddress: "192.168.1.21"
    installDisk: "/dev/sdb"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/25b18a561487b9b993d64a3fb9b9b8da8a35fc612ccb35db403cb87b37d24e7c
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "48:4d:7e:eb:ec:03"
        dhcp: false
        addresses:
          - "192.168.1.21/24"
        routes:
          - gateway: "192.168.1.1"
            network: 0.0.0.0/0
        mtu: 1500
        vip:
          ip: "192.168.1.20"
    patches:
      # Load kernel modules
      - |-
        machine:
          kernel:
            modules:
              - name: iscsi_tcp
  - hostname: "k8s-1"
    ipAddress: "192.168.1.22"
    installDisk: "/dev/sdb"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/25b18a561487b9b993d64a3fb9b9b8da8a35fc612ccb35db403cb87b37d24e7c
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "18:66:da:21:f7:b6"
        dhcp: false
        addresses:
          - "192.168.1.22/24"
        routes:
          - gateway: "192.168.1.1"
            network: 0.0.0.0/0
        mtu: 1500
        vip:
          ip: "192.168.1.20"
    patches:
      # Load kernel modules
      - |-
        machine:
          kernel:
            modules:
              - name: iscsi_tcp
  - hostname: "k8s-2"
    ipAddress: "192.168.1.23"
    installDisk: "/dev/sdb"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/25b18a561487b9b993d64a3fb9b9b8da8a35fc612ccb35db403cb87b37d24e7c
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "64:00:6a:91:97:9b"
        dhcp: false
        addresses:
          - "192.168.1.23/24"
        routes:
          - gateway: "192.168.1.1"
            network: 0.0.0.0/0
        mtu: 1500
        vip:
          ip: "192.168.1.20"
    patches:
      # Load kernel modules
      - |-
        machine:
          kernel:
            modules:
              - name: iscsi_tcp

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/cluster.yaml"

